import { fetchWeatherApi } from "openmeteo";

const params = {
	latitude: 52.52,
	longitude: 13.41,
	daily: ["weather_code", "temperature_2m_max", "apparent_temperature_max", "temperature_2m_min", "apparent_temperature_min", "sunrise", "sunset", "daylight_duration", "uv_index_max", "sunshine_duration", "uv_index_clear_sky_max", "rain_sum", "showers_sum", "snowfall_sum", "precipitation_sum", "precipitation_hours", "precipitation_probability_max", "wind_speed_10m_max", "wind_direction_10m_dominant", "wind_gusts_10m_max", "et0_fao_evapotranspiration", "shortwave_radiation_sum", "apparent_temperature_mean", "temperature_2m_mean", "cape_mean", "cloud_cover_max", "cape_min", "cape_max", "cloud_cover_mean", "cloud_cover_min", "dew_point_2m_mean", "dew_point_2m_max", "dew_point_2m_min", "et0_fao_evapotranspiration_sum", "leaf_wetness_probability_mean", "growing_degree_days_base_0_limit_50", "precipitation_probability_mean", "precipitation_probability_min", "relative_humidity_2m_mean", "relative_humidity_2m_max", "relative_humidity_2m_min", "snowfall_water_equivalent_sum", "pressure_msl_mean", "pressure_msl_max", "pressure_msl_min", "surface_pressure_mean", "surface_pressure_max", "surface_pressure_min", "updraft_max", "visibility_mean", "visibility_min", "visibility_max", "winddirection_10m_dominant", "wind_gusts_10m_mean", "wind_speed_10m_mean", "wind_speed_10m_min", "wind_gusts_10m_min", "wet_bulb_temperature_2m_mean", "wet_bulb_temperature_2m_max", "vapour_pressure_deficit_max", "wet_bulb_temperature_2m_min"],
	hourly: ["temperature_2m", "relative_humidity_2m", "dew_point_2m", "apparent_temperature", "precipitation_probability", "precipitation", "rain", "showers", "snowfall", "snow_depth", "weather_code", "pressure_msl", "surface_pressure", "cloud_cover", "cloud_cover_low", "cloud_cover_high", "visibility", "evapotranspiration", "et0_fao_evapotranspiration", "wind_speed_10m", "wind_speed_120m", "wind_speed_180m", "wind_speed_80m", "wind_direction_10m", "wind_direction_80m", "wind_direction_120m", "wind_direction_180m", "wind_gusts_10m", "temperature_80m", "temperature_120m", "temperature_180m", "soil_temperature_0cm", "soil_temperature_6cm", "soil_temperature_18cm", "soil_temperature_54cm", "soil_moisture_0_to_1cm", "soil_moisture_1_to_3cm", "soil_moisture_3_to_9cm", "soil_moisture_9_to_27cm", "soil_moisture_27_to_81cm", "shortwave_radiation", "direct_radiation", "diffuse_radiation", "terrestrial_radiation", "direct_normal_irradiance", "global_tilted_irradiance", "shortwave_radiation_instant", "direct_radiation_instant", "diffuse_radiation_instant", "direct_normal_irradiance_instant", "terrestrial_radiation_instant", "global_tilted_irradiance_instant", "temperature_1000hPa", "temperature_975hPa", "temperature_950hPa", "temperature_925hPa", "temperature_900hPa", "temperature_800hPa", "temperature_850hPa", "temperature_700hPa", "temperature_600hPa", "temperature_500hPa", "temperature_400hPa", "temperature_300hPa", "temperature_200hPa", "temperature_250hPa", "temperature_150hPa", "temperature_100hPa", "temperature_70hPa", "temperature_50hPa", "temperature_30hPa", "relative_humidity_1000hPa", "relative_humidity_975hPa", "relative_humidity_950hPa", "relative_humidity_925hPa", "relative_humidity_900hPa", "relative_humidity_850hPa", "relative_humidity_800hPa", "relative_humidity_700hPa", "relative_humidity_400hPa", "relative_humidity_500hPa", "relative_humidity_600hPa", "relative_humidity_300hPa", "relative_humidity_250hPa", "relative_humidity_200hPa", "relative_humidity_150hPa", "relative_humidity_100hPa", "relative_humidity_70hPa", "relative_humidity_50hPa", "relative_humidity_30hPa", "cloud_cover_950hPa", "cloud_cover_1000hPa", "cloud_cover_975hPa", "cloud_cover_925hPa", "cloud_cover_900hPa", "cloud_cover_850hPa", "cloud_cover_800hPa", "cloud_cover_700hPa", "cloud_cover_600hPa", "cloud_cover_500hPa", "cloud_cover_400hPa", "cloud_cover_300hPa", "cloud_cover_250hPa", "cloud_cover_200hPa", "cloud_cover_150hPa", "cloud_cover_100hPa", "cloud_cover_50hPa", "cloud_cover_70hPa", "cloud_cover_30hPa", "wind_speed_1000hPa", "wind_speed_975hPa", "wind_speed_950hPa", "wind_speed_900hPa", "wind_speed_925hPa", "wind_speed_850hPa", "wind_speed_800hPa", "wind_speed_700hPa", "wind_speed_500hPa", "wind_speed_600hPa", "wind_speed_400hPa", "wind_speed_300hPa", "wind_speed_250hPa", "wind_speed_200hPa", "wind_speed_70hPa", "wind_speed_150hPa", "wind_speed_100hPa", "wind_speed_50hPa", "wind_speed_30hPa", "wind_direction_1000hPa", "wind_direction_950hPa", "wind_direction_975hPa", "wind_direction_900hPa", "wind_direction_925hPa", "wind_direction_850hPa", "wind_direction_800hPa", "wind_direction_700hPa", "wind_direction_600hPa", "wind_direction_500hPa", "wind_direction_400hPa", "wind_direction_300hPa", "wind_direction_250hPa", "wind_direction_200hPa", "wind_direction_100hPa", "wind_direction_150hPa", "wind_direction_70hPa", "wind_direction_50hPa", "wind_direction_30hPa", "geopotential_height_950hPa", "geopotential_height_1000hPa", "geopotential_height_975hPa", "geopotential_height_925hPa", "geopotential_height_900hPa", "geopotential_height_800hPa", "geopotential_height_850hPa", "geopotential_height_700hPa", "geopotential_height_600hPa", "geopotential_height_500hPa", "geopotential_height_400hPa", "geopotential_height_300hPa", "geopotential_height_250hPa", "geopotential_height_200hPa", "geopotential_height_150hPa", "geopotential_height_100hPa", "geopotential_height_70hPa", "geopotential_height_50hPa", "geopotential_height_30hPa"],
	models: ["best_match", "ecmwf_ifs", "ecmwf_ifs025", "ecmwf_aifs025_single", "cma_grapes_global", "bom_access_global", "icon_seamless", "icon_global", "icon_eu", "icon_d2", "metno_seamless", "metno_nordic", "gfs_seamless", "gfs_global", "gfs_hrrr", "ncep_nbm_conus", "gfs_graphcast025", "gem_seamless", "ncep_nam_conus", "gem_regional", "gem_global", "gem_hrdps_continental", "gem_hrdps_west", "knmi_harmonie_arome_europe", "knmi_harmonie_arome_netherlands", "knmi_seamless", "dmi_seamless", "dmi_harmonie_arome_europe", "meteofrance_seamless", "jma_seamless", "jma_msm", "jma_gsm", "kma_seamless", "kma_ldps", "kma_gdps", "italia_meteo_arpae_icon_2i", "meteofrance_arpege_world", "meteofrance_arpege_europe", "meteofrance_arome_france", "meteofrance_arome_france_hd", "ukmo_seamless", "ukmo_global_deterministic_10km", "ukmo_uk_deterministic_2km", "meteoswiss_icon_seamless", "meteoswiss_icon_ch1", "meteoswiss_icon_ch2"],
	current: ["temperature_2m", "relative_humidity_2m", "apparent_temperature", "is_day", "precipitation", "rain", "showers", "snowfall", "weather_code", "cloud_cover", "pressure_msl", "surface_pressure", "wind_speed_10m", "wind_gusts_10m", "wind_direction_10m"],
	minutely_15: ["dew_point_2m", "temperature_2m", "relative_humidity_2m", "apparent_temperature", "precipitation", "shortwave_radiation", "direct_radiation", "diffuse_radiation", "direct_normal_irradiance", "terrestrial_radiation", "global_tilted_irradiance", "rain", "snowfall", "snowfall_height", "freezing_level_height", "sunshine_duration", "shortwave_radiation_instant", "direct_radiation_instant", "diffuse_radiation_instant", "direct_normal_irradiance_instant", "global_tilted_irradiance_instant", "terrestrial_radiation_instant", "weather_code", "wind_speed_10m", "wind_speed_80m", "wind_direction_10m", "wind_direction_80m", "wind_gusts_10m", "visibility", "cape", "lightning_potential", "is_day"],
	timezone: "Asia/Singapore",
	timeformat: "unixtime",
};
const url = "https://api.open-meteo.com/v1/forecast";
const responses = await fetchWeatherApi(url, params);

// Process 1 location and 46 models
for (const response of responses) {
	// Attributes for timezone and location
	const latitude = response.latitude();
	const longitude = response.longitude();
	const elevation = response.elevation();
	const timezone = response.timezone();
	const timezoneAbbreviation = response.timezoneAbbreviation();
	const utcOffsetSeconds = response.utcOffsetSeconds();
	
	console.log(
		`\nCoordinates: ${latitude}°N ${longitude}°E`,
		`\nElevation: ${elevation}m asl`,
		`\nTimezone: ${timezone} ${timezoneAbbreviation}`,
		`\nTimezone difference to GMT+0: ${utcOffsetSeconds}s`,
		`\nModel Nº: ${response.model()}`,
	);
	
	const current = response.current()!;
	const minutely15 = response.minutely15()!;
	const hourly = response.hourly()!;
	const daily = response.daily()!;
	
	// Define Int64 variables so they can be processed accordingly
	const sunrise = daily.variables(5)!;
	const sunset = daily.variables(6)!;
	
	// Note: The order of weather variables in the URL query and the indices below need to match!
	const weatherData = {
		current: {
			time: new Date((Number(current.time()) + utcOffsetSeconds) * 1000),
			temperature_2m: current.variables(0)!.value(),
			relative_humidity_2m: current.variables(1)!.value(),
			apparent_temperature: current.variables(2)!.value(),
			is_day: current.variables(3)!.value(),
			precipitation: current.variables(4)!.value(),
			rain: current.variables(5)!.value(),
			showers: current.variables(6)!.value(),
			snowfall: current.variables(7)!.value(),
			weather_code: current.variables(8)!.value(),
			cloud_cover: current.variables(9)!.value(),
			pressure_msl: current.variables(10)!.value(),
			surface_pressure: current.variables(11)!.value(),
			wind_speed_10m: current.variables(12)!.value(),
			wind_gusts_10m: current.variables(13)!.value(),
			wind_direction_10m: current.variables(14)!.value(),
		},
		minutely15: {
			time: Array.from(
				{ length: (Number(minutely15.timeEnd()) - Number(minutely15.time())) / minutely15.interval() }, 
				(_, i) => new Date((Number(minutely15.time()) + i * minutely15.interval() + utcOffsetSeconds) * 1000)
			),
			dew_point_2m: minutely15.variables(0)!.valuesArray(),
			temperature_2m: minutely15.variables(1)!.valuesArray(),
			relative_humidity_2m: minutely15.variables(2)!.valuesArray(),
			apparent_temperature: minutely15.variables(3)!.valuesArray(),
			precipitation: minutely15.variables(4)!.valuesArray(),
			shortwave_radiation: minutely15.variables(5)!.valuesArray(),
			direct_radiation: minutely15.variables(6)!.valuesArray(),
			diffuse_radiation: minutely15.variables(7)!.valuesArray(),
			direct_normal_irradiance: minutely15.variables(8)!.valuesArray(),
			terrestrial_radiation: minutely15.variables(9)!.valuesArray(),
			global_tilted_irradiance: minutely15.variables(10)!.valuesArray(),
			rain: minutely15.variables(11)!.valuesArray(),
			snowfall: minutely15.variables(12)!.valuesArray(),
			snowfall_height: minutely15.variables(13)!.valuesArray(),
			freezing_level_height: minutely15.variables(14)!.valuesArray(),
			sunshine_duration: minutely15.variables(15)!.valuesArray(),
			shortwave_radiation_instant: minutely15.variables(16)!.valuesArray(),
			direct_radiation_instant: minutely15.variables(17)!.valuesArray(),
			diffuse_radiation_instant: minutely15.variables(18)!.valuesArray(),
			direct_normal_irradiance_instant: minutely15.variables(19)!.valuesArray(),
			global_tilted_irradiance_instant: minutely15.variables(20)!.valuesArray(),
			terrestrial_radiation_instant: minutely15.variables(21)!.valuesArray(),
			weather_code: minutely15.variables(22)!.valuesArray(),
			wind_speed_10m: minutely15.variables(23)!.valuesArray(),
			wind_speed_80m: minutely15.variables(24)!.valuesArray(),
			wind_direction_10m: minutely15.variables(25)!.valuesArray(),
			wind_direction_80m: minutely15.variables(26)!.valuesArray(),
			wind_gusts_10m: minutely15.variables(27)!.valuesArray(),
			visibility: minutely15.variables(28)!.valuesArray(),
			cape: minutely15.variables(29)!.valuesArray(),
			lightning_potential: minutely15.variables(30)!.valuesArray(),
			is_day: minutely15.variables(31)!.valuesArray(),
		},
		hourly: {
			time: Array.from(
				{ length: (Number(hourly.timeEnd()) - Number(hourly.time())) / hourly.interval() }, 
				(_, i) => new Date((Number(hourly.time()) + i * hourly.interval() + utcOffsetSeconds) * 1000)
			),
			temperature_2m: hourly.variables(0)!.valuesArray(),
			relative_humidity_2m: hourly.variables(1)!.valuesArray(),
			dew_point_2m: hourly.variables(2)!.valuesArray(),
			apparent_temperature: hourly.variables(3)!.valuesArray(),
			precipitation_probability: hourly.variables(4)!.valuesArray(),
			precipitation: hourly.variables(5)!.valuesArray(),
			rain: hourly.variables(6)!.valuesArray(),
			showers: hourly.variables(7)!.valuesArray(),
			snowfall: hourly.variables(8)!.valuesArray(),
			snow_depth: hourly.variables(9)!.valuesArray(),
			weather_code: hourly.variables(10)!.valuesArray(),
			pressure_msl: hourly.variables(11)!.valuesArray(),
			surface_pressure: hourly.variables(12)!.valuesArray(),
			cloud_cover: hourly.variables(13)!.valuesArray(),
			cloud_cover_low: hourly.variables(14)!.valuesArray(),
			cloud_cover_high: hourly.variables(15)!.valuesArray(),
			visibility: hourly.variables(16)!.valuesArray(),
			evapotranspiration: hourly.variables(17)!.valuesArray(),
			et0_fao_evapotranspiration: hourly.variables(18)!.valuesArray(),
			wind_speed_10m: hourly.variables(19)!.valuesArray(),
			wind_speed_120m: hourly.variables(20)!.valuesArray(),
			wind_speed_180m: hourly.variables(21)!.valuesArray(),
			wind_speed_80m: hourly.variables(22)!.valuesArray(),
			wind_direction_10m: hourly.variables(23)!.valuesArray(),
			wind_direction_80m: hourly.variables(24)!.valuesArray(),
			wind_direction_120m: hourly.variables(25)!.valuesArray(),
			wind_direction_180m: hourly.variables(26)!.valuesArray(),
			wind_gusts_10m: hourly.variables(27)!.valuesArray(),
			temperature_80m: hourly.variables(28)!.valuesArray(),
			temperature_120m: hourly.variables(29)!.valuesArray(),
			temperature_180m: hourly.variables(30)!.valuesArray(),
			soil_temperature_0cm: hourly.variables(31)!.valuesArray(),
			soil_temperature_6cm: hourly.variables(32)!.valuesArray(),
			soil_temperature_18cm: hourly.variables(33)!.valuesArray(),
			soil_temperature_54cm: hourly.variables(34)!.valuesArray(),
			soil_moisture_0_to_1cm: hourly.variables(35)!.valuesArray(),
			soil_moisture_1_to_3cm: hourly.variables(36)!.valuesArray(),
			soil_moisture_3_to_9cm: hourly.variables(37)!.valuesArray(),
			soil_moisture_9_to_27cm: hourly.variables(38)!.valuesArray(),
			soil_moisture_27_to_81cm: hourly.variables(39)!.valuesArray(),
			shortwave_radiation: hourly.variables(40)!.valuesArray(),
			direct_radiation: hourly.variables(41)!.valuesArray(),
			diffuse_radiation: hourly.variables(42)!.valuesArray(),
			terrestrial_radiation: hourly.variables(43)!.valuesArray(),
			direct_normal_irradiance: hourly.variables(44)!.valuesArray(),
			global_tilted_irradiance: hourly.variables(45)!.valuesArray(),
			shortwave_radiation_instant: hourly.variables(46)!.valuesArray(),
			direct_radiation_instant: hourly.variables(47)!.valuesArray(),
			diffuse_radiation_instant: hourly.variables(48)!.valuesArray(),
			direct_normal_irradiance_instant: hourly.variables(49)!.valuesArray(),
			terrestrial_radiation_instant: hourly.variables(50)!.valuesArray(),
			global_tilted_irradiance_instant: hourly.variables(51)!.valuesArray(),
			temperature_1000hPa: hourly.variables(52)!.valuesArray(),
			temperature_975hPa: hourly.variables(53)!.valuesArray(),
			temperature_950hPa: hourly.variables(54)!.valuesArray(),
			temperature_925hPa: hourly.variables(55)!.valuesArray(),
			temperature_900hPa: hourly.variables(56)!.valuesArray(),
			temperature_800hPa: hourly.variables(57)!.valuesArray(),
			temperature_850hPa: hourly.variables(58)!.valuesArray(),
			temperature_700hPa: hourly.variables(59)!.valuesArray(),
			temperature_600hPa: hourly.variables(60)!.valuesArray(),
			temperature_500hPa: hourly.variables(61)!.valuesArray(),
			temperature_400hPa: hourly.variables(62)!.valuesArray(),
			temperature_300hPa: hourly.variables(63)!.valuesArray(),
			temperature_200hPa: hourly.variables(64)!.valuesArray(),
			temperature_250hPa: hourly.variables(65)!.valuesArray(),
			temperature_150hPa: hourly.variables(66)!.valuesArray(),
			temperature_100hPa: hourly.variables(67)!.valuesArray(),
			temperature_70hPa: hourly.variables(68)!.valuesArray(),
			temperature_50hPa: hourly.variables(69)!.valuesArray(),
			temperature_30hPa: hourly.variables(70)!.valuesArray(),
			relative_humidity_1000hPa: hourly.variables(71)!.valuesArray(),
			relative_humidity_975hPa: hourly.variables(72)!.valuesArray(),
			relative_humidity_950hPa: hourly.variables(73)!.valuesArray(),
			relative_humidity_925hPa: hourly.variables(74)!.valuesArray(),
			relative_humidity_900hPa: hourly.variables(75)!.valuesArray(),
			relative_humidity_850hPa: hourly.variables(76)!.valuesArray(),
			relative_humidity_800hPa: hourly.variables(77)!.valuesArray(),
			relative_humidity_700hPa: hourly.variables(78)!.valuesArray(),
			relative_humidity_400hPa: hourly.variables(79)!.valuesArray(),
			relative_humidity_500hPa: hourly.variables(80)!.valuesArray(),
			relative_humidity_600hPa: hourly.variables(81)!.valuesArray(),
			relative_humidity_300hPa: hourly.variables(82)!.valuesArray(),
			relative_humidity_250hPa: hourly.variables(83)!.valuesArray(),
			relative_humidity_200hPa: hourly.variables(84)!.valuesArray(),
			relative_humidity_150hPa: hourly.variables(85)!.valuesArray(),
			relative_humidity_100hPa: hourly.variables(86)!.valuesArray(),
			relative_humidity_70hPa: hourly.variables(87)!.valuesArray(),
			relative_humidity_50hPa: hourly.variables(88)!.valuesArray(),
			relative_humidity_30hPa: hourly.variables(89)!.valuesArray(),
			cloud_cover_950hPa: hourly.variables(90)!.valuesArray(),
			cloud_cover_1000hPa: hourly.variables(91)!.valuesArray(),
			cloud_cover_975hPa: hourly.variables(92)!.valuesArray(),
			cloud_cover_925hPa: hourly.variables(93)!.valuesArray(),
			cloud_cover_900hPa: hourly.variables(94)!.valuesArray(),
			cloud_cover_850hPa: hourly.variables(95)!.valuesArray(),
			cloud_cover_800hPa: hourly.variables(96)!.valuesArray(),
			cloud_cover_700hPa: hourly.variables(97)!.valuesArray(),
			cloud_cover_600hPa: hourly.variables(98)!.valuesArray(),
			cloud_cover_500hPa: hourly.variables(99)!.valuesArray(),
			cloud_cover_400hPa: hourly.variables(100)!.valuesArray(),
			cloud_cover_300hPa: hourly.variables(101)!.valuesArray(),
			cloud_cover_250hPa: hourly.variables(102)!.valuesArray(),
			cloud_cover_200hPa: hourly.variables(103)!.valuesArray(),
			cloud_cover_150hPa: hourly.variables(104)!.valuesArray(),
			cloud_cover_100hPa: hourly.variables(105)!.valuesArray(),
			cloud_cover_50hPa: hourly.variables(106)!.valuesArray(),
			cloud_cover_70hPa: hourly.variables(107)!.valuesArray(),
			cloud_cover_30hPa: hourly.variables(108)!.valuesArray(),
			wind_speed_1000hPa: hourly.variables(109)!.valuesArray(),
			wind_speed_975hPa: hourly.variables(110)!.valuesArray(),
			wind_speed_950hPa: hourly.variables(111)!.valuesArray(),
			wind_speed_900hPa: hourly.variables(112)!.valuesArray(),
			wind_speed_925hPa: hourly.variables(113)!.valuesArray(),
			wind_speed_850hPa: hourly.variables(114)!.valuesArray(),
			wind_speed_800hPa: hourly.variables(115)!.valuesArray(),
			wind_speed_700hPa: hourly.variables(116)!.valuesArray(),
			wind_speed_500hPa: hourly.variables(117)!.valuesArray(),
			wind_speed_600hPa: hourly.variables(118)!.valuesArray(),
			wind_speed_400hPa: hourly.variables(119)!.valuesArray(),
			wind_speed_300hPa: hourly.variables(120)!.valuesArray(),
			wind_speed_250hPa: hourly.variables(121)!.valuesArray(),
			wind_speed_200hPa: hourly.variables(122)!.valuesArray(),
			wind_speed_70hPa: hourly.variables(123)!.valuesArray(),
			wind_speed_150hPa: hourly.variables(124)!.valuesArray(),
			wind_speed_100hPa: hourly.variables(125)!.valuesArray(),
			wind_speed_50hPa: hourly.variables(126)!.valuesArray(),
			wind_speed_30hPa: hourly.variables(127)!.valuesArray(),
			wind_direction_1000hPa: hourly.variables(128)!.valuesArray(),
			wind_direction_950hPa: hourly.variables(129)!.valuesArray(),
			wind_direction_975hPa: hourly.variables(130)!.valuesArray(),
			wind_direction_900hPa: hourly.variables(131)!.valuesArray(),
			wind_direction_925hPa: hourly.variables(132)!.valuesArray(),
			wind_direction_850hPa: hourly.variables(133)!.valuesArray(),
			wind_direction_800hPa: hourly.variables(134)!.valuesArray(),
			wind_direction_700hPa: hourly.variables(135)!.valuesArray(),
			wind_direction_600hPa: hourly.variables(136)!.valuesArray(),
			wind_direction_500hPa: hourly.variables(137)!.valuesArray(),
			wind_direction_400hPa: hourly.variables(138)!.valuesArray(),
			wind_direction_300hPa: hourly.variables(139)!.valuesArray(),
			wind_direction_250hPa: hourly.variables(140)!.valuesArray(),
			wind_direction_200hPa: hourly.variables(141)!.valuesArray(),
			wind_direction_100hPa: hourly.variables(142)!.valuesArray(),
			wind_direction_150hPa: hourly.variables(143)!.valuesArray(),
			wind_direction_70hPa: hourly.variables(144)!.valuesArray(),
			wind_direction_50hPa: hourly.variables(145)!.valuesArray(),
			wind_direction_30hPa: hourly.variables(146)!.valuesArray(),
			geopotential_height_950hPa: hourly.variables(147)!.valuesArray(),
			geopotential_height_1000hPa: hourly.variables(148)!.valuesArray(),
			geopotential_height_975hPa: hourly.variables(149)!.valuesArray(),
			geopotential_height_925hPa: hourly.variables(150)!.valuesArray(),
			geopotential_height_900hPa: hourly.variables(151)!.valuesArray(),
			geopotential_height_800hPa: hourly.variables(152)!.valuesArray(),
			geopotential_height_850hPa: hourly.variables(153)!.valuesArray(),
			geopotential_height_700hPa: hourly.variables(154)!.valuesArray(),
			geopotential_height_600hPa: hourly.variables(155)!.valuesArray(),
			geopotential_height_500hPa: hourly.variables(156)!.valuesArray(),
			geopotential_height_400hPa: hourly.variables(157)!.valuesArray(),
			geopotential_height_300hPa: hourly.variables(158)!.valuesArray(),
			geopotential_height_250hPa: hourly.variables(159)!.valuesArray(),
			geopotential_height_200hPa: hourly.variables(160)!.valuesArray(),
			geopotential_height_150hPa: hourly.variables(161)!.valuesArray(),
			geopotential_height_100hPa: hourly.variables(162)!.valuesArray(),
			geopotential_height_70hPa: hourly.variables(163)!.valuesArray(),
			geopotential_height_50hPa: hourly.variables(164)!.valuesArray(),
			geopotential_height_30hPa: hourly.variables(165)!.valuesArray(),
		},
		daily: {
			time: Array.from(
				{ length: (Number(daily.timeEnd()) - Number(daily.time())) / daily.interval() }, 
				(_, i) => new Date((Number(daily.time()) + i * daily.interval() + utcOffsetSeconds) * 1000)
			),
			weather_code: daily.variables(0)!.valuesArray(),
			temperature_2m_max: daily.variables(1)!.valuesArray(),
			apparent_temperature_max: daily.variables(2)!.valuesArray(),
			temperature_2m_min: daily.variables(3)!.valuesArray(),
			apparent_temperature_min: daily.variables(4)!.valuesArray(),
			// Map Int64 values to according structure
			sunrise: [...Array(sunrise.valuesInt64Length())].map(
				(_, i) => new Date((Number(sunrise.valuesInt64(i)) + utcOffsetSeconds) * 1000)
			),
			// Map Int64 values to according structure
			sunset: [...Array(sunset.valuesInt64Length())].map(
				(_, i) => new Date((Number(sunset.valuesInt64(i)) + utcOffsetSeconds) * 1000)
			),
			daylight_duration: daily.variables(7)!.valuesArray(),
			uv_index_max: daily.variables(8)!.valuesArray(),
			sunshine_duration: daily.variables(9)!.valuesArray(),
			uv_index_clear_sky_max: daily.variables(10)!.valuesArray(),
			rain_sum: daily.variables(11)!.valuesArray(),
			showers_sum: daily.variables(12)!.valuesArray(),
			snowfall_sum: daily.variables(13)!.valuesArray(),
			precipitation_sum: daily.variables(14)!.valuesArray(),
			precipitation_hours: daily.variables(15)!.valuesArray(),
			precipitation_probability_max: daily.variables(16)!.valuesArray(),
			wind_speed_10m_max: daily.variables(17)!.valuesArray(),
			wind_direction_10m_dominant: daily.variables(18)!.valuesArray(),
			wind_gusts_10m_max: daily.variables(19)!.valuesArray(),
			et0_fao_evapotranspiration: daily.variables(20)!.valuesArray(),
			shortwave_radiation_sum: daily.variables(21)!.valuesArray(),
			apparent_temperature_mean: daily.variables(22)!.valuesArray(),
			temperature_2m_mean: daily.variables(23)!.valuesArray(),
			cape_mean: daily.variables(24)!.valuesArray(),
			cloud_cover_max: daily.variables(25)!.valuesArray(),
			cape_min: daily.variables(26)!.valuesArray(),
			cape_max: daily.variables(27)!.valuesArray(),
			cloud_cover_mean: daily.variables(28)!.valuesArray(),
			cloud_cover_min: daily.variables(29)!.valuesArray(),
			dew_point_2m_mean: daily.variables(30)!.valuesArray(),
			dew_point_2m_max: daily.variables(31)!.valuesArray(),
			dew_point_2m_min: daily.variables(32)!.valuesArray(),
			et0_fao_evapotranspiration_sum: daily.variables(33)!.valuesArray(),
			leaf_wetness_probability_mean: daily.variables(34)!.valuesArray(),
			growing_degree_days_base_0_limit_50: daily.variables(35)!.valuesArray(),
			precipitation_probability_mean: daily.variables(36)!.valuesArray(),
			precipitation_probability_min: daily.variables(37)!.valuesArray(),
			relative_humidity_2m_mean: daily.variables(38)!.valuesArray(),
			relative_humidity_2m_max: daily.variables(39)!.valuesArray(),
			relative_humidity_2m_min: daily.variables(40)!.valuesArray(),
			snowfall_water_equivalent_sum: daily.variables(41)!.valuesArray(),
			pressure_msl_mean: daily.variables(42)!.valuesArray(),
			pressure_msl_max: daily.variables(43)!.valuesArray(),
			pressure_msl_min: daily.variables(44)!.valuesArray(),
			surface_pressure_mean: daily.variables(45)!.valuesArray(),
			surface_pressure_max: daily.variables(46)!.valuesArray(),
			surface_pressure_min: daily.variables(47)!.valuesArray(),
			updraft_max: daily.variables(48)!.valuesArray(),
			visibility_mean: daily.variables(49)!.valuesArray(),
			visibility_min: daily.variables(50)!.valuesArray(),
			visibility_max: daily.variables(51)!.valuesArray(),
			winddirection_10m_dominant: daily.variables(52)!.valuesArray(),
			wind_gusts_10m_mean: daily.variables(53)!.valuesArray(),
			wind_speed_10m_mean: daily.variables(54)!.valuesArray(),
			wind_speed_10m_min: daily.variables(55)!.valuesArray(),
			wind_gusts_10m_min: daily.variables(56)!.valuesArray(),
			wet_bulb_temperature_2m_mean: daily.variables(57)!.valuesArray(),
			wet_bulb_temperature_2m_max: daily.variables(58)!.valuesArray(),
			vapour_pressure_deficit_max: daily.variables(59)!.valuesArray(),
			wet_bulb_temperature_2m_min: daily.variables(60)!.valuesArray(),
		},
	};
	
	// The 'weatherData' object now contains a simple structure, with arrays of datetimes and weather information
	console.log(
		`\nCurrent time: ${weatherData.current.time}\n`,
		`\nCurrent temperature_2m: ${weatherData.current.temperature_2m}`,
		`\nCurrent relative_humidity_2m: ${weatherData.current.relative_humidity_2m}`,
		`\nCurrent apparent_temperature: ${weatherData.current.apparent_temperature}`,
		`\nCurrent is_day: ${weatherData.current.is_day}`,
		`\nCurrent precipitation: ${weatherData.current.precipitation}`,
		`\nCurrent rain: ${weatherData.current.rain}`,
		`\nCurrent showers: ${weatherData.current.showers}`,
		`\nCurrent snowfall: ${weatherData.current.snowfall}`,
		`\nCurrent weather_code: ${weatherData.current.weather_code}`,
		`\nCurrent cloud_cover: ${weatherData.current.cloud_cover}`,
		`\nCurrent pressure_msl: ${weatherData.current.pressure_msl}`,
		`\nCurrent surface_pressure: ${weatherData.current.surface_pressure}`,
		`\nCurrent wind_speed_10m: ${weatherData.current.wind_speed_10m}`,
		`\nCurrent wind_gusts_10m: ${weatherData.current.wind_gusts_10m}`,
		`\nCurrent wind_direction_10m: ${weatherData.current.wind_direction_10m}`,
	);
	console.log("\nMinutely15 data:\n", weatherData.minutely15)
	console.log("\nHourly data:\n", weatherData.hourly)
	console.log("\nDaily data:\n", weatherData.daily)
}